name: env variable testing

on:
  workflow_dispatch
  
env:
  address: new-20
  
jobs:
  run-add:
    runs-on: ubuntu-latest
    
    steps:
     - name: checkout
       uses: actions/checkout@v4
       
     - name: environment variable checking
       run: echo "$address"

     - name: secret-checking
       run: echo "{{vars.NEWBIE}"
    
