name: env variable testing

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      number1:
        description: "First Number"
        required: true
      number2:
        description: "Second Number"
        required: true

jobs:
  pop-ups:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: retrive
        run: echo ${{ inputs.number1 }}
        
      - name: retrive1
        run: echo ${{ inputs.number2 }}
        
   

